#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_FTS) += fts_ts.o 
fts_ts-y += focaltech_core.o focaltech_ctl.o focaltech_ex_fun.o focaltech_flash.o test_lib.o Global.o DetailThreshold.o Config_FT5X46.o Test_FT5X46.o ini.o

extlibs := $(PWD)/drivers/input/touchscreen/ft5446/ft_gesture_64bit_lib_v1.0_20140820.a
ldflags_fts_ts.o := --whole-archive $(extlibs) --no-whole-archive